### PR TITLE
Slot repeated

### PR DESCRIPTION
**Pull request by gaelb80**
The AlRepeatedSlotsManager does not take care about custom themes.base_dir

### CODE REVIEW

**Comment by alphalemon** [comment]
Hello! 
Really thank you for interesting in AlphaLemon CMS. I noticed you are very active now, so let me stop you a moment to avoid wasting your time! :-)

Actually the CMS is in high revision phase and the preview release you are working on is really out of date. The branch where all these changes are taking place is the revisioning-cms-objects one. Objects have been improved and decoupled, a strong test suite has been written and actually it has 500+ tests and 2000+ assertions.

Last week I tried to make it working with travis-ci but a lot of thirdy part bundles/libraries the cms depends on, have problems with the symfony 2.1 package, because it seems it didn't exist when I tried, so actually I don't know if you are able to set up a working environment using that branch, but if you will try and you will make it work, you will help me a lot!!

ThemeEngine have been revisited too and themes structure have been totally redesigned. I need to write down some unit tests before committing them and I hope to be able to release those changes today.

**Comment by gaelb80** [comment]
ok no problem i try to switch to active branch to test it and i'll give you feedback

**Comment by gaelb80** [comment]
Starting to install cms in sf 2.1 branch and the specified branch for the cms
Just added for the moment the "alphalemon/alphalemon-cms-bundle": "dev-revisioning-cms-object" to my composer and update my project
Remembering the install script i try to find the equivalent in the bundle, find in bin - ok.
Watching script to have an idea of the stuff it do and find that the Installer class is not present in bundle
Waiting for you to resolve the problem.
Regards

**Comment by alphalemon** [comment]
The installer script had been replaced by a dedicated bundle. I've updated the composer.json to retrieve the installer too, but, at the moment, I'm not able to install from composer.phar because I got dependencies errors: is it working for you?

Please notice that I've just updated the changes on ThemeEngine I told you this morning.
Thanks!

**Comment by alphalemon** [comment]
The installer script had been replaced by a dedicated bundle. I've updated the composer.json to retrieve the installer too, but, at the moment, I'm not able to install from composer.phar because I got dependencies errors: is it working for you?

Please notice that I've just updated the changes on ThemeEngine I told you this morning.
Thanks!

**Comment by gaelb80** [comment]
see dev mailing list to continue discuss

**Pull request closed without merging**
